# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Btsland' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.3'

  # Pods for Btsland

  target 'BtslandTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Btsland-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Btsland-tvOS

  target 'Btsland-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
